name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hex: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_code_scanner: ^1.0.1
  web3auth_flutter: ^3.1.1
  web3dart: ^2.7.2
  web3modal_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/